### ISSUE TITLE
Support the concept of multidimensional block

### ISSUE THREAD

**Issue by FrancescAlted** [FrancescAlted/caterva#13]
It should be useful to have another layer of chunking when defining the partitions.  Blosc2 splits frames in chunks and blocks; right now, only the chunks can be multidimensional in Caterva.  The idea would be add this multidimensionality capability to the blocks too, and also enable the slice selection machinery to use that for reducing the amount of data to be read.

**Comment by FrancescAlted** [comment]
Space for storing a multidimensional block has been added in commit afc305e (Carterva 0.2.0).

**Comment by aleixalcacer** [comment]
Fixed in #36
