### ISSUE TITLE
Support to add partitions to an empty schunk

### ISSUE THREAD

**Issue by aleixalcacer** [FrancescAlted/caterva#3]
It would be desirable to be able to fill an empty matrix (superchunk) with a caterva method. For that, the following three methods would be necessary:

- `caterva_has_next()`: It indicates if the array is filled or if some partition is missing.
- `caterva_next()`: It indicates the shape of the next block and the position of the first element in the array.
- `caterva_append()`: A block buffer will be passed with the shape given by the above function.

The use of this methods would be:

```
while(caterva_has_next()) {
    caterva_next()
    ...
    caterva_append()
}
```

**Comment by FrancescAlted** [comment]
Initially we have alternate ways to fill the matrix, like `caterva_append()` and `caterva_set_slice_buffer ()` (for caterva arrays bcked by a plain buffer), so I am adding the low-priority tag here.

**Comment by aleixalcacer** [comment]
Outdated!
