### ISSUE TITLE
Missing splitmode and compcodecmeta parameters at caterva_config_t

### ISSUE THREAD

**Issue by oscargm98** [FrancescAlted/caterva#68]
There are two new parameters we have to add to caterva_config_t structure (in caterva.h) in order to make the udcodecs system work correctly.
We must implement them in CATERVA_CONFIG_DEFAULTS (caterva.h) and caterva_blosc_array_empty (caterva_blosc.c) too:

![image](https://user-images.githubusercontent.com/45040313/117786130-7e840180-b245-11eb-9026-065c64c9604c.png)

![image](https://user-images.githubusercontent.com/45040313/117786397-be4ae900-b245-11eb-9c7a-5bc0f48d5215.png)

![image](https://user-images.githubusercontent.com/45040313/117786665-0b2ebf80-b246-11eb-9c59-017524c96102.png)

**Comment by aleixalcacer** [comment]
done!
