### ISSUE TITLE
Update caterva_fill

### ISSUE THREAD

**Issue by aleixalcacer** [FrancescAlted/caterva#9]
Update `caterva_fill` using the method `caterva_append`. Another option is remove this method.

**Comment by FrancescAlted** [comment]
If there is a clear duplicity of intent and `caterva_append` can do everything, then I'm +1 in removing `caterva_fill` (there should be one, and preferably only one, way to do things).

**Comment by FrancescAlted** [comment]
After more reflection, I am thinking that `caterva_fill()` still has an extra of functionality beyond `caterva_append()` that can be useful for users.  So I changed my mind and I'd vote for `caterva_fill()` to stay, unless @aleix11alcacer has other reasons for removing it.  However, it still would be nice if `caterva_fill()` can be implemented in terms of `caterva_append()`.

**Comment by aleixalcacer** [comment]
I think that if a fill method is implemented, we also need to implement other constructors such as an arange or a linspace. So I hold my position about it.

**Comment by FrancescAlted** [comment]
Yes, I think you are right.  Lets' remove `caterva_fill()` then.

**Comment by aleixalcacer** [comment]
Removed
