### ISSUE TITLE
Caterva frees

### ISSUE THREAD

**Issue by oscargm98** [FrancescAlted/caterva#98]
In caterva.h there are two free functions with parameters that I am not sure if have the correct structures:
int caterva_ctx_free(caterva_ctx_t **ctx);
int caterva_free(caterva_ctx_t *ctx, caterva_array_t **array);

Is it right that the structures are ** instead of *?

**Comment by FrancescAlted** [comment]
We discussed that internally, and decided that we want to continue using this convention.  Closing.
