### ISSUE TITLE
caterva_resize API

### ISSUE THREAD

**Issue by aleixalcacer** [FrancescAlted/caterva#99]
Up to now, in Caterva the first parameter of every function is a `caterva_ctx_t *` (it contains malloc/free functions along with other general parameters).

I think we should consider adding it to `caterva_resize` to unify the design. 

What is your point of view? @FrancescAlted @martaiborra

**Comment by FrancescAlted** [comment]
Agreed.

**Comment by martaiborra** [comment]
Done in PR #100 .

**Comment by FrancescAlted** [comment]
Fixed in #100
